version: "1.0"
services:
  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    network_mode: "host"
    volumes:
      - /srv/dev-disk-by-uuid-1b1fb1b6-788a-463f-9226-00ef8d47d8c5/dockerData/lychee/config:/conf
      - /srv/dev-disk-by-uuid-1b1fb1b6-788a-463f-9226-00ef8d47d8c5/dockerData/lychee/cache:/uploads
      - /srv/dev-disk-by-uuid-1b1fb1b6-788a-463f-9226-00ef8d47d8c5/dockerData/lychee/media:/sym

    restart: "unless-stopped"
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900/udp
      - 7359:7359/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai