version: "3.5"
services:
  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    network_mode: "bridge"
    volumes:
      - /srv/dev-disk-by-uuid-1b1fb1b6-788a-463f-9226-00ef8d47d8c5/dockerData/lychee/config:/conf
      - /srv/dev-disk-by-uuid-1b1fb1b6-788a-463f-9226-00ef8d47d8c5/dockerData/lychee/cache:/uploads
      - /srv/dev-disk-by-uuid-1b1fb1b6-788a-463f-9226-00ef8d47d8c5/dockerData/lychee/media:/sym
    restart: "unless-stopped"
    ports:
      - 90:80
    environment:
      - PUID=1000
      - PGID=1000
      - PHP_TZ=Asia/Shanghai
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.1.88 
      - DB_PORT=3306 
      - DB_DATABASE=lychee 
      - DB_USERNAME=root 
      - DB_PASSWORD=admin