# https://github.com/hacdias/webdav
services:
  webdav:
    image: hacdias/webdav:latest
    container_name: webdav
    restart: always
    user: "1000:1000"
    # 挂载配置文件和数据目录
    volumes:
      - ${WEBDAV_CONFIG_PATH:-./config.yaml}:/config.yaml:ro
      - ${WEBDAV_DATA_PATH:-./data}:/data
    # 指定容器启动时读取刚才的配置文件
    command: ["--config", "/config.yaml"]